### ISSUE TITLE
goupy.py plante avec les caractères accentués dans la propriété `filename`

### ISSUE THREAD

**Issue by chrnin** [signaux-faibles/prepare-import#47]
J'obtiens ce message:
```
Traceback (most recent call last):
  File "tools/goupy.py", line 50, in <module>
    main()
  File "tools/goupy.py", line 23, in main
    writer.writerow(d)
  File "/usr/lib64/python2.7/csv.py", line 148, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 7: ordinal not in range(128)
```

pour ce fichier de propriétés où on retrouver des accents dans le nom de fichier (`Ellisphère-Tête de groupe-FinalV2-2015.xlsx`):
```
{"ID":"3bf7f0f805a66926452321b77ec0c1db","Size":12337702,"SizeIsDeferred":false,"Offset":0,"MetaData":{"email":"----------","filename":"Ellisphère-Tête de groupe-FinalV2-2015.xlsx","filetype":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","goup-path":"signauxfaibles","private":"false"},"IsPartial":false,"IsFinal":false,"PartialUploads":null,"Storage":{"Path":"/var/lib/goup_base/tusd/3bf7f0f805a66926452321b77ec0c1db","Type":"filestore"}}
```

**Comment by adrienjoly** [comment]
Merci pour ce rapport d'erreur, Christophe !

Question, au passage: je viens de voir que ce script goupy est aussi stocké dans le dépot de goup: https://github.com/signaux-faibles/goup/tree/master/tools/goupy (c'est une version plus ancienne, et plus courte de deux lignes)

Je suggère qu'on ne garde qu'un seul de ces deux fichiers, pour éviter toute confusion, et erreur qui pourrait en résulter.

Est-ce qu'on supprime celui du dépot goup ?

**Comment by chrnin** [comment]
oui, on peut supprimer celui de goup.

**Comment by adrienjoly** [comment]
Merci pour ta réponse ! J'y ai ouvert un pull request, du coup.

Et je vais m'occuper de ce ticket dans la foulée, pour nous permettre d'intégrer Ellisphère dans prepare-import.
