### ISSUE TITLE
lecture du fichier effectif 

### ISSUE THREAD

**Issue by chrnin** [signaux-faibles/prepare-import#61]
Bonjour,

prepare-import n'a pas l'air de correctement prendre en compte le format gzip pour la constitution des dates de fin d'effectifs et le fichier filtre.

C'est quelque chose que j'avais déjà constaté les mois précédents et je passais outre en décompressant le fichier.

```
$ sudo ./prepare-import -batch 2104_1_urssaf -path /var/lib/goup_base/public/
Listing data files in 2104_1_urssaf/ ...
Found effectif file: 719776012f6a124c3fab0f1c74fd585a
Generating filter file: /2104_1_urssaf/filter_siren_2104_1_urssaf.csv ...
2021/04/19 08:15:59 record on line 2: wrong number of fields
panic: record on line 2: wrong number of fields
```

**Comment by adrienjoly** [comment]
Merci pour l'info ! C'est corrigé dans PR #62.
